---
title: 'EDA: movie genres'
author: "Group 34 Chen/Ho/Jay"
date: "4/5/2017"
output: html_document
---
```{r, echo=F, include=FALSE}

library(TMDb)
library(plyr)
library(dplyr)
library(tidyr)
library(reshape2)

api_key <- "c7b4559008a651ec1173162071aec8e0"

#download genre list
genres <- genres_movie_list(api_key)
genres <- genres$genres

#load our dataset
our10000 <- read.csv("~/Documents/DrPH_open/Data Science 2/Final project/Milestone 1/movies_10000.csv")

#convert genre ids from factor
genre_ids <- gsub("\\[|\\]", "", our10000$genre_ids)

#remove brackets
genre_ids <- strsplit(genre_ids, ", ")

#convert to dataframe (numeric)
n.obs <- sapply(genre_ids, length)
seq.max <- seq_len(max(n.obs))
genre <- t(sapply(genre_ids, "[", i = seq.max))
class(genre) <- "numeric"
genre <- as.data.frame(genre)
genres[20, ] <- c("10769", "Foreign") # this was missing

genre.named <- genre # duplicate table

#apply lookup function
genre.named[] <- lapply(genre, function(x) genres$name[match(x, genres$id)])

#create counts by genre
genre.wide <- cbind(movie_id=seq(1, nrow(genre.named)), genre.named) # add title
genre.long <- gather(genre.wide, key="movie_id", value="genre", na.rm=T) #reshape to long
genre.long <- genre.long[order(genre.long$movie_id),] #reorder for visual check

genre.count <- dcast(movie_id~genre, data=genre.long[, c(1,3)], 
                     fun.aggregate= length,value.var = 'genre')
#only 9703 of the 10,032 movies (97%) had genre

#add "movie_id" to our movies
our10000$movie_id <- seq(1, nrow(our10000))

genre.count <- left_join(our10000[, c("title", "movie_id")], genre.count, by="movie_id")


```

```{r, echo=F}
library(ggplot2)

## compare number of assigned genres
g.counts <- as.data.frame(table(n.obs))

ggplot(g.counts, aes(x=n.obs, y=Freq)) + geom_bar(stat="identity") +
  labs(title="How many genres are assigned to each movie?",
       x="Assigned genres", y="Movies (of 10,0000 in sample)",
       caption="Source: TMDB data") + theme_minimal()

```
```{r, echo=F}

## compare genres by occurrence
genre.sums <- apply(genre.count[, 3:22], 2, FUN = sum, na.rm=T)
genre.sums <- data.frame(genre = genres$name, total = genre.sums)

ggplot(genre.sums, aes(x=reorder(genre, total), y=total)) + geom_bar(stat="identity") + coord_flip() + labs(x="", y="Frequency", title="Which genres are most common?", subtitle="Within our sample of the 1000 most popular movies each year 2006-2016", caption="Source: TMDb API") + theme_minimal()
```

```{r, echo=F, warning=F}
#pull all data together
dat <- left_join(our10000, genre.count, by=c("title", "movie_id"))
dat.long <- left_join(genre.long[, c(1, 3)], our10000, by="movie_id")
g.pop <- ddply(dat.long, .(genre), summarize, med.pop=median(popularity, na.rm = T))
dat.long <- left_join(dat.long, g.pop, by="genre")

ggplot(dat.long, aes(x=reorder(factor(genre), med.pop), y=log(popularity))) + geom_boxplot() + ylim(0, 2.5) + coord_flip() + theme_minimal() + labs(title="Which genres are most popular?", y="Log popularity", x="", subtitle="According to median popularity score", caption="\n(Movies with multiple genres counted in multiple categories)\n\nSource: TMDb") 
```
